/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_the5zig_mod_manager_keyboard_RoccatController */

#ifndef _Included_eu_the5zig_mod_manager_keyboard_RoccatController
#define _Included_eu_the5zig_mod_manager_keyboard_RoccatController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_the5zig_mod_manager_keyboard_RoccatController
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_eu_the5zig_mod_manager_keyboard_RoccatController_init
  (JNIEnv *, jobject);

/*
 * Class:     eu_the5zig_mod_manager_keyboard_RoccatController
 * Method:    unInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_the5zig_mod_manager_keyboard_RoccatController_unInit
  (JNIEnv *, jobject);

/*
 * Class:     eu_the5zig_mod_manager_keyboard_RoccatController
 * Method:    setIlluminatedKeys
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_eu_the5zig_mod_manager_keyboard_RoccatController_setIlluminatedKeys
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     eu_the5zig_mod_manager_keyboard_RoccatController
 * Method:    setShowHealth
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_eu_the5zig_mod_manager_keyboard_RoccatController_setShowHealth
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     eu_the5zig_mod_manager_keyboard_RoccatController
 * Method:    setShowArmor
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_eu_the5zig_mod_manager_keyboard_RoccatController_setShowArmor
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     eu_the5zig_mod_manager_keyboard_RoccatController
 * Method:    updateHealthAndArmor
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_eu_the5zig_mod_manager_keyboard_RoccatController_updateHealthAndArmor
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     eu_the5zig_mod_manager_keyboard_RoccatController
 * Method:    onDamage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_the5zig_mod_manager_keyboard_RoccatController_onDamage
  (JNIEnv *, jobject);

/*
 * Class:     eu_the5zig_mod_manager_keyboard_RoccatController
 * Method:    displayPotionColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_eu_the5zig_mod_manager_keyboard_RoccatController_displayPotionColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     eu_the5zig_mod_manager_keyboard_RoccatController
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_the5zig_mod_manager_keyboard_RoccatController_update
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
