---
name: Mod compatibility
about: Report a compatibility issue.
title: 'Mod Compat: '
labels: Compatibility
assignees: ''

---

**What mod is causing it?**
Please provide enough details for us to download the specific version of the mod that's causing it.  
A link to the mod's source code would be appreciated too.

**Does the mod load?**

**Does 5zig load?**

**Which features of the mod don't work?**

**Which features of 5zig don't work?**

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04]
 - Version [e.g. 3.26.x]

**Additional context**
Add any other context about the problem here.
