/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_the5zig_mod_manager_WindowsMediaPlayerManager */

#ifndef _Included_eu_the5zig_mod_manager_WindowsMediaPlayerManager
#define _Included_eu_the5zig_mod_manager_WindowsMediaPlayerManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_the5zig_mod_manager_WindowsMediaPlayerManager
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_the5zig_mod_manager_WindowsMediaPlayerManager_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
