/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_the5zig_mod_manager_keyboard_RazerController */

#ifndef _Included_eu_the5zig_mod_manager_keyboard_RazerController
#define _Included_eu_the5zig_mod_manager_keyboard_RazerController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_the5zig_mod_manager_keyboard_RazerController
 * Method:    init0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_eu_the5zig_mod_manager_keyboard_RazerController_init0
  (JNIEnv *, jobject);

/*
 * Class:     eu_the5zig_mod_manager_keyboard_RazerController
 * Method:    unInit0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_eu_the5zig_mod_manager_keyboard_RazerController_unInit0
  (JNIEnv *, jobject);

/*
 * Class:     eu_the5zig_mod_manager_keyboard_RazerController
 * Method:    setIlluminatedKeys
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_eu_the5zig_mod_manager_keyboard_RazerController_setIlluminatedKeys
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     eu_the5zig_mod_manager_keyboard_RazerController
 * Method:    setShowHealth
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_eu_the5zig_mod_manager_keyboard_RazerController_setShowHealth
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     eu_the5zig_mod_manager_keyboard_RazerController
 * Method:    setShowArmor
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_eu_the5zig_mod_manager_keyboard_RazerController_setShowArmor
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     eu_the5zig_mod_manager_keyboard_RazerController
 * Method:    updateHealthAndArmor
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_eu_the5zig_mod_manager_keyboard_RazerController_updateHealthAndArmor
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     eu_the5zig_mod_manager_keyboard_RazerController
 * Method:    onDamage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_the5zig_mod_manager_keyboard_RazerController_onDamage
  (JNIEnv *, jobject);

/*
 * Class:     eu_the5zig_mod_manager_keyboard_RazerController
 * Method:    displayPotionColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_eu_the5zig_mod_manager_keyboard_RazerController_displayPotionColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     eu_the5zig_mod_manager_keyboard_RazerController
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_the5zig_mod_manager_keyboard_RazerController_update
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class eu_the5zig_mod_manager_keyboard_RazerController_RazerResult */

#ifndef _Included_eu_the5zig_mod_manager_keyboard_RazerController_RazerResult
#define _Included_eu_the5zig_mod_manager_keyboard_RazerController_RazerResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
